spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
axon:
  axonserver:
    enabled: false
  kafka:
    fetcher:
      enabled: false
    publisher:
      enabled: false
application:
  disable-kafka: true