application:
  kafka:
    topics: user-service-topic, payment-service-topic, pubsubdoc-service-topic
axon:
  kafka:
    client-id: user-service-web
    producer:
      retries: 0
    consumer:
      event-processor-mode: tracking
    properties:
      security.protocol: PLAINTEXT
    default-topic: user-service-topic
    bootstrap-servers: localhost:29092,localhost:29192,localhost:29292
