application:
  kafka:
    topics: doc-service-topic, payment-service-topic, pubsubdoc-service-topic, user-service-topic
axon:
  kafka:
    client-id: pubsubdoc-service-back
    producer:
      retries: 0
    consumer:
      event-processor-mode: tracking
    properties:
      security.protocol: PLAINTEXT
    default-topic: pubsubdoc-service-topic
    bootstrap-servers: localhost:29092,localhost:29192,localhost:29292
